-- AlterTable
ALTER TABLE "User" ADD COLUMN     "aiAnalysisCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "hasSubscription" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "lastAnalysisReset" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
